/* Shared district list used across superadmin pages */
const DISTRICTS = [

 // ANDHRA PRADESH (26)
 "Srikakulam",
 "Parvathipuram Manyam",
 "Vizianagaram",
 "Visakhapatnam",
 "Anakapalli",
 "Alluri Sitharama Raju",
 "Kakinada",
 "Dr. B.R. Ambedkar Konaseema",
 "East Godavari",
 "Eluru",
 "West Godavari",
 "NTR",
 "Krishna",
 "Guntur",
 "Palnadu",
 "Bapatla",
 "Prakasam",
 "Sri Potti Sriramulu Nellore",
 "Kurnool",
 "Nandyal",
 "Anantapur",
 "Sri Sathya Sai",
 "YSR Kadapa",
 "Annamayya",
 "Tirupati",
 "Chittoor",

 // TELANGANA (33)
 "Adilabad",
 "Bhadradri Kothagudem",
 "Hanumakonda",
 "Hyderabad",
 "Jagtial",
 "Jangaon",
 "Jayashankar Bhupalpally",
 "Jogulamba Gadwal",
 "Kamareddy",
 "Karimnagar",
 "Khammam",
 "Kumuram Bheem Asifabad",
 "Mahabubabad",
 "Mahabubnagar",
 "Mancherial",
 "Medak",
 "Medchal Malkajgiri",
 "Mulugu",
 "Nagarkurnool",
 "Nalgonda",
 "Narayanpet",
 "Nirmal",
 "Nizamabad",
 "Peddapalli",
 "Rajanna Sircilla",
 "Rangareddy",
 "Sangareddy",
 "Siddipet",
 "Suryapet",
 "Vikarabad",
 "Wanaparthy",
 "Warangal",
 "Yadadri Bhuvanagiri"
];
